import test from 'node:test';
import assert from 'node:assert/strict';
import { normalizeFeatures, validateFeatures, ruleCandidate } from '../src/features.js';
import { calculateLots, evaluateRisk } from '../src/risk.js';
import { validateFundamentalSourceFreshness, enforceFundamentalSafety } from '../src/ai.js';

const base = {
  bid: 3000, ask: 3000.3, point: 0.01, spread: 0.3, spread_points: 30, bar_time: Math.floor(Date.now()/1000)-30,
  m5:{ema20:3001,ema50:2999,rsi14:45,atr14:3,high20:3005,low20:2995},
  h1:{ema20:3010,ema50:3005,ema200:2990,rsi14:58,atr14:8}
};
test('features validate',()=>{const f=normalizeFeatures(base);assert.deepEqual(validateFeatures(f),[]);});
test('rule candidate identifies bullish setup',()=>assert.equal(ruleCandidate(normalizeFeatures(base)),'BUY'));
test('lot calculation returns stepped size without exceeding risk',()=>{const r=calculateLots({equity:10000,riskPct:0.25,entry:3000,stopLoss:2995,tickSize:0.01,tickValue:1,minLot:0.01,maxLot:100,lotStep:0.01});assert.ok(r.lots>0);assert.ok(r.lots<=r.rawLots);});
test('WAIT is never approved',()=>{const f=normalizeFeatures(base);const r=evaluateRisk({decision:{decision:'WAIT',confidence:1},features:f,account:{},signalCreatedAt:Date.now(),now:Date.now()});assert.equal(r.approved,false);});
test('confidence above 1 is blocked',()=>{const f=normalizeFeatures(base);const r=evaluateRisk({decision:{decision:'BUY',candidate:'BUY',confidence:1.2,risk_reward:2,entry:3000,stop_loss:2995,take_profit:3010},features:f,account:{equity:10000,open_positions:0,daily_pnl_pct:0,drawdown_pct:0,risk_data_ready:true,trade_allowed:1,tick_size:0.01,tick_value:1,min_lot:0.01,max_lot:100,lot_step:0.01},signalCreatedAt:Date.now(),now:Date.now()});assert.equal(r.approved,false);});
test('bad BUY price geometry is blocked',()=>{const f=normalizeFeatures(base);const r=evaluateRisk({decision:{decision:'BUY',candidate:'BUY',confidence:.8,risk_reward:2,entry:3000,stop_loss:3001,take_profit:3010},features:f,account:{equity:10000,open_positions:0,daily_pnl_pct:0,drawdown_pct:0,risk_data_ready:true,trade_allowed:1,tick_size:.01,tick_value:1,min_lot:.01,max_lot:100,lot_step:.01},signalCreatedAt:Date.now(),now:Date.now()});assert.equal(r.approved,false);});
test('daily loss blocks new order',()=>{const f=normalizeFeatures(base);const r=evaluateRisk({decision:{decision:'BUY',candidate:'BUY',confidence:.8,risk_reward:2,entry:3000,stop_loss:2995,take_profit:3010},features:f,account:{equity:10000,open_positions:0,daily_pnl_pct:-2.1,drawdown_pct:0,risk_data_ready:true,trade_allowed:1,tick_size:.01,tick_value:1,min_lot:.01,max_lot:100,lot_step:.01},signalCreatedAt:Date.now(),now:Date.now()});assert.equal(r.approved,false);});
test('broker trade permission blocks order',()=>{const f=normalizeFeatures(base);const r=evaluateRisk({decision:{decision:'BUY',candidate:'BUY',confidence:.8,risk_reward:2,entry:3000,stop_loss:2995,take_profit:3010},features:f,account:{equity:10000,open_positions:0,daily_pnl_pct:0,drawdown_pct:0,risk_data_ready:true,trade_allowed:0,tick_size:.01,tick_value:1,min_lot:.01,max_lot:100,lot_step:.01},signalCreatedAt:Date.now(),now:Date.now()});assert.equal(r.approved,false);});
test('stale bar blocks order',()=>{const f=normalizeFeatures({...base,bar_time:Math.floor(Date.now()/1000)-1000});const r=evaluateRisk({decision:{decision:'BUY',candidate:'BUY',confidence:.8,risk_reward:2,entry:3000,stop_loss:2995,take_profit:3010},features:f,account:{equity:10000,open_positions:0,daily_pnl_pct:0,drawdown_pct:0,risk_data_ready:true,trade_allowed:1,tick_size:.01,tick_value:1,min_lot:.01,max_lot:100,lot_step:.01},signalCreatedAt:Date.now(),now:Date.now()});assert.equal(r.approved,false);});
test('strongly conflicting fundamentals block a BUY',()=>{const f=normalizeFeatures(base);const r=evaluateRisk({decision:{decision:'BUY',candidate:'BUY',confidence:.8,risk_reward:2,entry:3000,stop_loss:2995,take_profit:3010,fundamental:{bias:'BEARISH_GOLD',confidence:.8,freshness:'CURRENT'}},features:f,account:{equity:10000,open_positions:0,daily_pnl_pct:0,drawdown_pct:0,risk_data_ready:true,trade_allowed:1,tick_size:.01,tick_value:1,min_lot:.01,max_lot:100,lot_step:.01},signalCreatedAt:Date.now(),now:Date.now()});assert.ok(r.reasons.includes('fundamental_conflict'));assert.equal(r.approved,false);});
test('strongly aligned fundamentals do not add a conflict',()=>{const f=normalizeFeatures(base);const r=evaluateRisk({decision:{decision:'BUY',candidate:'BUY',confidence:.8,risk_reward:2,entry:3000,stop_loss:2995,take_profit:3010,fundamental:{bias:'BULLISH_GOLD',confidence:.8,freshness:'CURRENT'}},features:f,account:{equity:10000,open_positions:0,daily_pnl_pct:0,drawdown_pct:0,risk_data_ready:true,trade_allowed:1,tick_size:.01,tick_value:1,minLot:.01,maxLot:100,lotStep:.01},signalCreatedAt:Date.now(),now:Date.now()});assert.ok(!r.reasons.includes('fundamental_conflict'));});
test('missing fundamentals block a BUY',()=>{const f=normalizeFeatures(base);const r=evaluateRisk({decision:{decision:'BUY',candidate:'BUY',confidence:.8,risk_reward:2,entry:3000,stop_loss:2995,take_profit:3010},features:f,account:{equity:10000,open_positions:0,daily_pnl_pct:0,drawdown_pct:0,risk_data_ready:true,trade_allowed:1,tick_size:.01,tick_value:1,min_lot:.01,max_lot:100,lot_step:.01},signalCreatedAt:Date.now(),now:Date.now()});assert.ok(r.reasons.includes('fundamental_data_insufficient'));assert.equal(r.approved,false);});


test('valid BUY with aligned current fundamentals is approved',()=>{const f=normalizeFeatures(base);const r=evaluateRisk({decision:{decision:'BUY',candidate:'BUY',confidence:.8,risk_reward:2,entry:3000.3,stop_loss:2995.3,take_profit:3010.3,fundamental:{bias:'BULLISH_GOLD',confidence:.8,freshness:'CURRENT'}},features:f,account:{equity:10000,open_positions:0,daily_pnl_pct:0,drawdown_pct:0,risk_data_ready:true,trade_allowed:1,tick_size:.01,tick_value:1,min_lot:.01,max_lot:100,lot_step:.01},signalCreatedAt:Date.now(),now:Date.now()});assert.equal(r.approved,true);assert.ok(r.lots>0);assert.equal(r.actualRR,2);});
test('wide spread blocks otherwise valid BUY',()=>{const f=normalizeFeatures({...base,spread:.6});const r=evaluateRisk({decision:{decision:'BUY',candidate:'BUY',confidence:.8,risk_reward:2,entry:3000.3,stop_loss:2995.3,take_profit:3010.3,fundamental:{bias:'BULLISH_GOLD',confidence:.8,freshness:'CURRENT'}},features:f,account:{equity:10000,open_positions:0,daily_pnl_pct:0,drawdown_pct:0,risk_data_ready:true,trade_allowed:1,tick_size:.01,tick_value:1,min_lot:.01,max_lot:100,lot_step:.01},signalCreatedAt:Date.now(),now:Date.now()});assert.ok(r.reasons.includes('spread_too_wide'));assert.equal(r.approved,false);});
test('maximum open positions blocks otherwise valid BUY',()=>{const f=normalizeFeatures(base);const r=evaluateRisk({decision:{decision:'BUY',candidate:'BUY',confidence:.8,risk_reward:2,entry:3000.3,stop_loss:2995.3,take_profit:3010.3,fundamental:{bias:'BULLISH_GOLD',confidence:.8,freshness:'CURRENT'}},features:f,account:{equity:10000,open_positions:1,daily_pnl_pct:0,drawdown_pct:0,risk_data_ready:true,trade_allowed:1,tick_size:.01,tick_value:1,min_lot:.01,max_lot:100,lot_step:.01},signalCreatedAt:Date.now(),now:Date.now()});assert.ok(r.reasons.includes('max_open_positions'));assert.equal(r.approved,false);});
test('stale fundamentals block otherwise valid BUY',()=>{const f=normalizeFeatures(base);const r=evaluateRisk({decision:{decision:'BUY',candidate:'BUY',confidence:.8,risk_reward:2,entry:3000.3,stop_loss:2995.3,take_profit:3010.3,fundamental:{bias:'BULLISH_GOLD',confidence:.8,freshness:'STALE'}},features:f,account:{equity:10000,open_positions:0,daily_pnl_pct:0,drawdown_pct:0,risk_data_ready:true,trade_allowed:1,tick_size:.01,tick_value:1,min_lot:.01,max_lot:100,lot_step:.01},signalCreatedAt:Date.now(),now:Date.now()});assert.ok(r.reasons.includes('fundamental_data_insufficient'));assert.equal(r.approved,false);});
test('safeDecision preserves fundamental structure',async()=>{const {safeDecision}=await import('../src/risk.js');const d=safeDecision({decision:'BUY',confidence:.8,market_regime:'TREND_UP',entry:3000,stop_loss:2995,take_profit:3010,risk_reward:2,reason:'ok',invalid_reasons:[],fundamental:{bias:'BULLISH_GOLD',confidence:.82,freshness:'CURRENT',summary:'supportive',drivers:['y'],risks:['z']}});assert.equal(d.fundamental.bias,'BULLISH_GOLD');assert.equal(d.fundamental.confidence,.82);assert.equal(d.fundamental.freshness,'CURRENT');assert.deepEqual(d.fundamental.drivers,['y']);assert.deepEqual(d.fundamental.risks,['z']);});
test('WAIT with low confidence is rejected only for decision_wait',()=>{const f=normalizeFeatures(base);const r=evaluateRisk({decision:{decision:'WAIT',confidence:0},features:f,account:{},signalCreatedAt:Date.now(),now:Date.now()});assert.deepEqual(r.reasons,['decision_wait']);assert.equal(r.approved,false);});
test('current fundamental requires a date-verifiable recent source',()=>{const now=new Date('2026-10-01T12:00:00Z');const ok=validateFundamentalSourceFreshness([{url:'https://www.federalreserve.gov/newsevents/speech/barr20261001a.htm'}],'CURRENT',now,48);assert.equal(ok.ok,true);});
test('old dated source cannot certify current fundamental',()=>{const now=new Date('2026-10-01T12:00:00Z');const r=validateFundamentalSourceFreshness([{url:'https://www.federalreserve.gov/monetarypolicy/pressreleases/monetary20260916a.htm'}],'CURRENT',now,48);assert.equal(r.ok,false);assert.equal(r.reason,'fundamental_current_source_not_date_verifiable');});
test('neutral source freshness does not require current date evidence',()=>{const now=new Date('2026-10-01T12:00:00Z');const r=validateFundamentalSourceFreshness([{url:'https://www.gold.org/goldhub/data/gold-etfs-holdings-and-flows'}],'STALE',now,48);assert.equal(r.ok,true);});

test('unverifiable current source forces BUY to WAIT instead of throwing',()=>{const d={decision:'BUY',confidence:.8,entry:3000,stop_loss:2995,take_profit:3010,risk_reward:2,invalid_reasons:[],fundamental:{bias:'BULLISH_GOLD',confidence:.8,freshness:'CURRENT',summary:'x',drivers:[],risks:[],source_urls:[]}};const r=enforceFundamentalSafety(d,{ok:false,reason:'fundamental_current_source_not_date_verifiable'});assert.equal(r.decision,'WAIT');assert.equal(r.entry,0);assert.equal(r.fundamental.freshness,'INSUFFICIENT');assert.ok(r.invalid_reasons.includes('fundamental_current_source_not_date_verifiable'));});
